[package]
name = "wavefront_align"
version = "0.1.0"
edition = "2021"
license = "MIT"
license_file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
